### ISSUE TITLE
Missing create_dataset.py file in the src/dataset directory

### ISSUE THREAD

**Issue by cgyzfjm** [shahriar0651/VehiGAN#2]
Hello,

I noticed that in the src/run_ind_training_pipeline.py script, there is a reference to dataset.create_dataset. However, upon checking the src/dataset directory, it seems that the create_dataset.py file is missing.

Could you please clarify the following:

Should the create_dataset.py file be included in the repository?
If not, could you provide instructions on how to generate or obtain this file?
Alternatively, is there another file (e.g., load_dataset.py) that should be used instead of create_dataset?

**Comment by shahriar0651** [comment]
Hi, Thanks for pointing out the issue. There was a bug as the `create_dataset.py` file was unnecessary for running that script. I have fixed that issue and, at the same time, have updated the whole project pipeline with much clarity and instructions. Please follow the current version (pull the recent updates).

**Comment by cgyzfjm** [comment]
> Hi, Thanks for pointing out the issue. There was a bug as the `create_dataset.py` file was unnecessary for running that script. I have fixed that issue and, at the same time, have updated the whole project pipeline with much clarity and instructions. Please follow the current version (pull the recent updates).

Thank you very much for your reply.😊
